/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_jsdirentry_is_directory: (a: number) => number;
export const __wbg_get_jsstat_is_directory: (a: number) => number;
export const __wbg_get_jsstat_mtime: (a: number) => bigint;
export const __wbg_get_jsstat_size: (a: number) => bigint;
export const __wbg_jsdirentry_free: (a: number, b: number) => void;
export const __wbg_jsstat_free: (a: number, b: number) => void;
export const __wbg_opfsvirtiodevice_free: (a: number, b: number) => void;
export const __wbg_set_jsdirentry_is_directory: (a: number, b: number) => void;
export const __wbg_set_jsstat_is_directory: (a: number, b: number) => void;
export const __wbg_set_jsstat_mtime: (a: number, b: bigint) => void;
export const __wbg_set_jsstat_size: (a: number, b: bigint) => void;
export const jsdirentry_name: (a: number) => [number, number];
export const opfsvirtiodevice_close: (a: number, b: bigint) => [number, number];
export const opfsvirtiodevice_exists: (a: number, b: number, c: number) => any;
export const opfsvirtiodevice_flush: (a: number, b: bigint) => [number, number];
export const opfsvirtiodevice_mkdir: (a: number, b: number, c: number) => any;
export const opfsvirtiodevice_new: () => any;
export const opfsvirtiodevice_open: (a: number, b: number, c: number, d: number) => any;
export const opfsvirtiodevice_read: (a: number, b: bigint, c: bigint, d: number) => [number, number, number, number];
export const opfsvirtiodevice_readdir: (a: number, b: number, c: number) => any;
export const opfsvirtiodevice_rename: (a: number, b: number, c: number, d: number, e: number) => any;
export const opfsvirtiodevice_rmdir: (a: number, b: number, c: number) => any;
export const opfsvirtiodevice_size: (a: number, b: bigint) => [number, number, number];
export const opfsvirtiodevice_stat: (a: number, b: number, c: number) => any;
export const opfsvirtiodevice_unlink: (a: number, b: number, c: number) => any;
export const opfsvirtiodevice_write: (a: number, b: bigint, c: bigint, d: number, e: number) => [number, number, number];
export const __wbg_createsyncaccesshandleoptions_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2bc0e6398e1271c8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hbcce4d867924b2d0: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb227545cd5b14f5f: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
